### ISSUE TITLE
Upgrade okteto/rust to 1.47.0

### ISSUE THREAD

**Issue by mibes** [okteto/devenv#79]
Can you re-release the okteto/rust container, such that it uses Rust 1.47.0?

Does it make sense to include an explicit Rust version tag on the Docker container, something like: `image: okteto/rust:1.47.0`?

This makes it more transparent to the developer which Rust version is being used.

Thanks!

BTW - awesome concept. It makes the (Rust) developers much more productive!

**Comment by pchico83** [comment]
@mibes sorry, the image is still building, I will let you know once it is ready

**Comment by pchico83** [comment]
@mibes it is now available.
I also pushed `okteto/rust:1.47.0` manually while we work on supporting different version tags automatically.
