### ISSUE TITLE
okteto container for .net 6

### ISSUE THREAD

**Issue by rberrelleza** [okteto/devenv#90]

**Comment by alanmbarr** [comment]
bump https://devblogs.microsoft.com/dotnet/announcing-net-6/

**Comment by rberrelleza** [comment]
we were just waiting for the official drop. container should be available by EOD @alanmbarr

**Comment by rberrelleza** [comment]
@alanmbarr do you think we should keep the dotnet3 container around?

**Comment by alanmbarr** [comment]
@rberrelleza I would keep one around because enterprises have a bad habit of leaving old stuff around. We're probably going to have at least 32 applications using okteto and .net core 3.1 until they decide to upgrade.
